name: concepta_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  async: ^2.10.0
  flutter:
    sdk: flutter
  intl: ^0.18.0
  pub_api_client: ^2.4.0
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
